// <auto-generated />
using FutureCodersWebApi.Repositories;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FutureCodersWebApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20240226145218_seedData")]
    partial class seedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FutureCodersWebApi.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CourseDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CourseThumbnail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRequire")
                        .HasColumnType("bit");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseDescription = "This course is a react course",
                            CourseName = "React",
                            CourseThumbnail = "",
                            IsRequire = true,
                            Rank = 2
                        },
                        new
                        {
                            Id = 2,
                            CourseDescription = "This course is a flutter course",
                            CourseName = "Flutter",
                            CourseThumbnail = "",
                            IsRequire = false,
                            Rank = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseDescription = "This course is a bootstrap 5 course",
                            CourseName = "Bootstrap",
                            CourseThumbnail = "",
                            IsRequire = false,
                            Rank = 2
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
